version: '2.1'
services:

  app:
    build: .
    container_name: shaunasaservice-website
    image: forward-motion/shaunasaservice-website
    command: npm run build
    env_file: .env.development
    ports:
      - '8000:8000'
    links:
    - lambda
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  lambda:
    build: .
    container_name: shaunasaservice-website-back-end
    image: forward-motion/shaunasaservice-website-back-end
    command: npm run lambda
    env_file: .env.development
    ports:
      - '9000:9000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules